-- This file previously contained a one-off net.http_post invocation with a
-- hardcoded service_role JWT in the Authorization header. The token was
-- leaked into git history.
--
-- As of 2026-04-30, that JWT no longer authenticates against any of our
-- edge functions: cron-triggered functions now require the
-- INTERNAL_CRON_TOKEN shared secret (stored in Vault, rotatable on demand)
-- via supabase/functions/_shared/internalAuth.ts.
--
-- The leaked JWT remains valid as a signed token (we cannot rotate the
-- project's signing keys ourselves), but direct PostgREST/SQL access via
-- the JWT is blocked by Row-Level Security on every public table.
--
-- See CHANGELOG.md (2026-04-30) for the full remediation.
SELECT 1;
